from external_data.mentor_forms.parser.Interspeech_2022_one_to_one_mentoring import parse_isca_2022_mentor_form_1_to_1_from_csv
from external_data.mentor_forms.parser.Interspeech_2022_round_table_mentoring import parse_isca_2022_mentor_form_rounf_table_from_csv

__all__ = ["parse_isca_2022_mentor_form_rounf_table_from_csv", "parse_isca_2022_mentor_form_rounf_table_from_csv"]
