# Generated by Django 4.0.3 on 2022-05-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admineventregistration',
            name='person_pkey',
        ),
        migrations.RemoveField(
            model_name='menteeeventregistration',
            name='person_pkey',
        ),
        migrations.RemoveField(
            model_name='mentoreventregistration',
            name='person_pkey',
        ),
    ]
